AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Darven API - FastAPI Application on Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11
    Environment:
      Variables:
        DATABASE_URL: !Ref DatabaseURL
        S3_BUCKET_NAME: !Ref S3BucketName
        AWS_REGION: !Ref AWS::Region
        JWT_SECRET_KEY: !Ref JWTSecretKey
        JWT_ALGORITHM: HS256
        ACCESS_TOKEN_EXPIRE_MINUTES: 30
        ALLOWED_ORIGINS: !Ref AllowedOrigins

Parameters:
  DatabaseURL:
    Type: String
    Description: PostgreSQL database connection URL
    NoEcho: true
  
  S3BucketName:
    Type: String
    Description: S3 bucket name for file uploads
  
  JWTSecretKey:
    Type: String
    Description: Secret key for JWT token generation
    NoEcho: true
  
  AllowedOrigins:
    Type: String
    Description: Comma-separated list of allowed CORS origins
    Default: "https://shopdarven.netlify.app"

Resources:
  DarvenAPI:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: darven-api
      CodeUri: .
      Handler: lambda_handler.handler
      Description: Darven FastAPI application
      Architectures:
        - x86_64
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:PutObjectAcl
              Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'
      # Uncomment VpcConfig if your RDS is in a VPC
      # VpcConfig:
      #   SecurityGroupIds:
      #     - sg-xxxxxxxxx
      #   SubnetIds:
      #     - subnet-xxxxxxxxx
      #     - subnet-yyyyyyyyy

  # S3 Bucket for uploads
  DarvenUploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  # Bucket policy to allow public read access
  DarvenUploadsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DarvenUploadsBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'

Outputs:
  DarvenApiUrl:
    Description: API Gateway endpoint URL for Darven API
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
  
  DarvenApiFunctionArn:
    Description: Darven API Lambda Function ARN
    Value: !GetAtt DarvenAPI.Arn
  
  S3BucketName:
    Description: S3 bucket for file uploads
    Value: !Ref DarvenUploadsBucket
